### ISSUE TITLE
Missing deployment method

### ISSUE THREAD

**Issue by jhibbets** [ALM-Rangers/Guidance#55]
I think you've forgot to specify which method, ring or flag, in this paragraph:

"We use the ??? to progressively expose a new release in production"

**Comment by jhibbets** [comment]
This is in regards to [rings-or-feature-flags.md](https://github.com/ALM-Rangers/Guidance/blob/af192cf56bec8deb06dc1b4b033e0d8c1a3759a2/src/Stories/rings-or-feature-flags.md)

**Comment by wpschaub** [comment]
Thanks! I replaced "the" with "both" in this [commit](https://github.com/ALM-Rangers/Guidance/blob/05dbdaa4703e6ab83fe74f958ceebc9f9068fe55/src/Stories/rings-or-feature-flags.md).
